services:
#    ens_jobeet.example:
#        class: Ens\JobeetBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  Ens\JobeetBundle\DataFixtures\ORM\LoadCategoryData:
    tags: [doctrine.fixture.orm]
  Ens\JobeetBundle\DataFixtures\ORM\LoadJobData:
    tags: [doctrine.fixture.orm]
    